meta_product_name: "Surf Your Trip"
meta_title: "Surf Your Trip - Organize your next ğŸ„â€â™‚ï¸ trip!"
meta_description: "Surf Your Trip is the bible for all â“¢â“¤â“¡â“•â“”â“¡â“¢ around ğŸŒ"
meta_image: "logo-meta.png" # should exist in `app/assets/images/`
